on:
  workflow_dispatch:
    inputs:
      deploy_env:
        description: 'Deploy environment'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - staging

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      deploy_env: ${{ inputs.deploy_env }}
    secrets:
      cognito_app_secret: ${{ secrets.cognito_app_secret }}
      aws_access_key_id: ${{ secrets.aws_access_key_id }}
      aws_secret_access_key: ${{ secrets.aws_secret_access_key }}
      stac_ingestor_url: ${{ secrets.stac_ingestor_url }}
      external_role_arn: ${{ secrets.external_role_arn }}
